//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpenLayersWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Log> Logs { get; set; }
    
        public virtual ObjectResult<GetSpatialData_Result> GetSpatialData(Nullable<decimal> x1, Nullable<decimal> x2, Nullable<decimal> y1, Nullable<decimal> y2)
        {
            var x1Parameter = x1.HasValue ?
                new ObjectParameter("x1", x1) :
                new ObjectParameter("x1", typeof(decimal));
    
            var x2Parameter = x2.HasValue ?
                new ObjectParameter("x2", x2) :
                new ObjectParameter("x2", typeof(decimal));
    
            var y1Parameter = y1.HasValue ?
                new ObjectParameter("y1", y1) :
                new ObjectParameter("y1", typeof(decimal));
    
            var y2Parameter = y2.HasValue ?
                new ObjectParameter("y2", y2) :
                new ObjectParameter("y2", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetSpatialData_Result>("GetSpatialData", x1Parameter, x2Parameter, y1Parameter, y2Parameter);
        }
    }
}
